spring:
  datasource:
    url: jdbc:mysql://153.92.220.201:3306/u319455556_training_db?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: u319455556_training_rw
    password: Mysql01#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
  hikari:
    minIdle: 10
    idle-timeout: 10000
    maximumPoolSize: 30

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8080

flickr:
  apiKey: e6017aef7bebeffc113de04efec554b4
  apiSecret: a2e10f69ece5c67c
  appKey: 72157718699655397-a36ae267891db7e7
  appSecret: 04e870e57e18c55b