name: SSH Deploy to Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: SSH key
        uses: ./
        eval: $(ssh-agent -s)
        with: 
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY }}
      - run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} raphael_de_castro@34.155.130.100
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
      - name: Validation
        run: |
          mkdir /raphael_de_castro/Validation.txt