name: deploy-docker-container
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Docker
      run: |
        sudo apt-get update 
        sudo apt-get install -y docker.io
    - name: Connect to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: raphaeldecastro/parking-web:latest
    - name: Deploy with Metadata Action
        uses: docker/metadata-action@v3
        with:
          images: raphaeldecastro/parking-web:$ {{ github.sha }}
          project-id: ${{ secrets.PROJECT_ID }}
          region: ${{ secrets.REGION }}
          service-name: parkingwebtest-${{ github.sha }}
