on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH key
        uses: ./
        with: 
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Set up SSH key 2
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
          chmod 600 deploy_key
          ssh-add deploy_key
      - name : Connexion en SSH
        run : |
          ssh -o StrictHostKeyChecking=no -p 22 raphael_de_castro@34.155.130.100
      - name: Install Docker
        run: |
          sudo apt-get -y update 
          sudo apt install -y docker.io
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: |
          sudo docker pull parking-web
      - name: Create a container with the pulled image
        run: |
          sudo docker run -d --name parking-web-container -p 3000:3000 parking-web
