name: SSH Deploy to Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Configure SSH
        env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: SSH into remote server and execute commands
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} raphael_de_castro@34.155.130.100 "echo 'Deployed via SSH.'"