name: deploy-docker-container
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Connect to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy with Metadata Action
        uses: docker/metadata-action@v3
        with:
          images: docker.io/${{ secrets.DOCKER_USERNAME }}/parkingwebtest:latest
          project-id: ${{ secrets.PROJECT_ID }}
          region: ${{ secrets.REGION }}
          service-name: parkingwebtest