on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install ssh-agent and add the private key to the agent
      - name: SSH configure 
        run: |
          mkdir -p ~/.ssh
          echo " ${{ secrets.DEPLOY_KEY }}" > deploy_key
          chmod 600 ~/.ssh
          eval "$(ssh-agent -s)"
          sudo ssh-add ~/.ssh/deploy_key

      - name: Configure ssh for known_hosts
        run: ssh-keyscan 34.155.130.100 >> ~/.ssh/known_hosts

      - name: Connect to remote server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key raphael_de_castro@34.155.130.100 "echo Connected! ; ls -la"

      # Install Docker on the remote server (if needed)
      - name: Install Docker
        run: |
          sudo apt-get update && \
          sudo apt-get install --yes apt-transport-https ca-certificates curl software-properties-common gnupg2 lsb-release && \
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
          sudo apt-get update && \
          sudo apt-get install --yes docker-ce docker-ce-cli containerd.io

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull the Docker image from Docker Hub
      - name: Pull Docker image
        run: |
          sudo docker pull parking-web

      # Run the Docker container
      - name: Run Docker container
        run: |
          sudo docker run -d --name parking-web-container -p 3000:3000 parking-web