on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install ssh-agent and add the private key to the agent
      - name: SSH configure 
        run: |
          eval "$(ssh-agent -s)"
        
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploiUbuntu
          chmod 600 ~/.ssh/deploiUbuntu
          ssh-add ~/.ssh/deploiUbuntu

      - name : SSH into the server and run commands
        uses: appleboy/ssh-action@master 
        with:
          host: ubuntuparkingwebtest
          key: ${{ secrets.DEPLOY_KEY }} # Le nom du secret contenant la clé privée SSH
          username: raphael_de_castro # L'utilisateur qui se connectera via ssh
          port: 22 # Si vous utilisez un port différent, modifiez-le ici.
          script: |
            sudo apt-get -y update
            sudo apt-get install -y docker.io curl 

      - name: Connect to remote server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key raphael_de_castro@34.155.130.100 "echo Connected! ; ls -la"

      # Install Docker on the remote server (if needed)
      - name: Install Docker
        run: |
          sudo apt-get update && \
          sudo apt-get install --yes apt-transport-https ca-certificates curl software-properties-common gnupg2 lsb-release && \
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
          sudo apt-get update && \
          sudo apt-get install --yes docker-ce docker-ce-cli containerd.io

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull the Docker image from Docker Hub
      - name: Pull Docker image
        run: |
          sudo docker pull parking-web

      # Run the Docker container
      - name: Run Docker container
        run: |
          sudo docker run -d --name parking-web-container -p 3000:3000 parking-web