name: deploy-docker-container
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Docker
      run: |
        sudo apt-get update 
        sudo apt-get install -y docker.io
    - name: Deploy using Docker/Metadata Actions 
      uses: docker/metadata-action@v3
      with:
        images: raphaeldecastro/parking-web:latest
        project-id: ${{ secrets.PROJECT_ID }}
        region: ${{ secrets.REGION }}
        service-name: ubuntuparkingwebtest
