name: SSH login

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest        
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: login
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} raphael_de_castro@34.155.130.100