name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  ssh_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install and start SSH agent
      - name: Start SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh/deploiUbuntu
          chmod 700 ~/.ssh
          ssh-keyscan 34.155.130.100 >> ~/.ssh/authorized_keys
          echo "${{ secrets.DEPLOY_KEY }}" > /home/raphael_de_castro/.ssh/deploiUbuntu
          chmod 600 /home/raphael_de_castro/.ssh/deploiUbuntu
          ssh-add /home/raphael_de_castro/.ssh/deploiUbuntu

      # SSH into the server
      - name: SSH into the server
        uses: appleboy/ssh-action@master
        with:
          username: 'raphael_de_castro'
          host: '34.155.130.100'
          key: ${{ secrets.DEPLOY_KEY }}
          port: '22'