on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Log into remote server using an SSH key.
      #
      # Replace `YOUR_SERVER_IP_ADDRESS` and `22` with the IP address of your remote server
      # and the port number of your SSH service if different from 22, respectively.
      #
      # Replace `id_rsa` with the private key filename if other than default and the secret
      # name 'DEPLOY_KEY' with the secret name you used above when creating the secret
      - name: Set up SSH key
        uses: ./
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        run : |
          ssh -i ${{ secrets.DEPLOY_KEY }} -p 22 raphael_de_castro@34.155.130.100

  Docker:
    Set-up:
      runs-on: ubuntu-latest
      steps:
        - name: Install Docker
          uses: actions/checkout@v2
          run: |
            sudo apt-get -y update 
            sudo apt install -y docker.io
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Pull image from docker hub
          run: |
            sudo docker pull parking-web
        - name: Create a container with the pulled image
          run: |
            sudo docker run -d --name parking-web-container -p 3000:3000 parking-web
