on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : Connexion en SSH
        run : |
          ssh -i ${{ secrets.DEPLOY_KEY }} raphael_de_castro@34.155.130.100
      - name: Install Docker
        run: |
          sudo apt-get -y update 
          sudo apt install -y docker.io
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: |
          sudo docker pull parking-web
      - name: Create a container with the pulled image
        run: |
          sudo docker run -d --name parking-web-container -p 3000:3000 parking-web
