name: SSH login

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest        
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mise en place
        env: 
          ssh_key: ${{secrets.DEPLOY_KEY}}
        run: |
          sudo mkdir /ParkingWeb/ssh
          touch deploiUbuntu
          echo $ssh_key > deploiUbuntu
      - name: Login
        run: |
          ssh -i /ParkingWeb/.ssh/deploiUbuntu raphael_de_castro@34.155.130.100