name: SSH login

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest        
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: login
        env: 
          ssh_key: ${{secrets.DEPLOY_KEY}}
        run: |
          ssh -i $ssh_key raphael_de_castro@34.155.130.100