name: SSH Deploy to Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: SSH into remote server and execute commands
        with: 
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        run: |
          ssh raphael_de_castro@34.155.130.100