name: deploy-docker-container
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: raphaeldecastro/parking-web:latest
      - name: Connect to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}
      - name: Deploy with Metadata Action
        uses: docker/metadata-action@v3
        with:
          images: gcr.io/${{ secrets.PROJECT_ID }}/parkingwebtest:latest
          project-id: ${{ secrets.PROJECT_ID }}
          region: ${{ secrets.REGION }}
          service-name: parkingwebtest